### ISSUE TITLE
Build on Emulator failing (starting at branch `release/2.4.x`)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2862]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Emulator
- iOS version: 14.5
- App version: 2.4

## Describe the bug

The App does not build. 
The console shows this output:

```
2021-06-07 21:02:37.515427+0200 ENA[28946:4750169] [ENA/Globals.swift:33] [fatalError(_:file:line:)] 💥 Fatal Error: Error parsing server environments: keyNotFound(CodingKeys(stringValue: "dccURL", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "environments", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"dccURL\", intValue: nil) (\"dccURL\").", underlyingError: nil))
ENA/Globals.swift:34: Fatal error: Error parsing server environments: keyNotFound(CodingKeys(stringValue: "dccURL", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "environments", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"dccURL\", intValue: nil) (\"dccURL\").", underlyingError: nil))
2021-06-07 21:02:37.516357+0200 ENA[28946:4750169] ENA/Globals.swift:34: Fatal error: Error parsing server environments: keyNotFound(CodingKeys(stringValue: "dccURL", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "environments", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"dccURL\", intValue: nil) (\"dccURL\").", underlyingError: nil))
(lldb) 
```

## Steps to reproduce the issue

1. Clone the repository.
2. Open the project in Xcode
3. Build the app
4. See the issue after the "device" can already be seen on the screen

## Expected behaviour

App should build as intended.

## Additional context

The build is working with the `release/2.3.x` branch, but `release/2.4.x` & `release/2.5.x` are not working.

**Comment by ndegendogo** [comment]
I also cannot build at release/2.4.x branch, as of yesterday evening.
It seems to miss the HealthCertificateToolkit in the package loading step. But I see the sources of this package. 
Error message: Package loading: Misding package product 'HealthCertificateToolkit'
Do I miss a specific build step / setup / preparation / or configuration?

**Comment by marcussc** [comment]
You have to delete the Enviroments.json a new one with the correct config will be generated on the next build.

**Comment by whiskey** [comment]
Deleting (or updating) the `Environments.json` file. We don't do a 'migration' of your personal local configuration and ended up with this situation for every developer.

The other issue @ndegendogo described is something completely different and more related to the discussion in #2880. @Ein-Tim I see build errors for the community build because the swift package seems to be created with `testability = false`. This results in errors when using `@testable` in our configuration… Nasty thing but I'm on this.

**Comment by whiskey** [comment]
Can you guys please check if 
1. deleting/updating the `Environments.json` helps AND
2. if the `fix/community-build-june-edition` branch does solve the errors in case 1.) failed?

Thanks in advance!

**Comment by Ein-Tim** [comment]
I'm still seeing the same error @whiskey 😕

**Comment by whiskey** [comment]
Ok @Ein-Tim, this is what Marcus mentioned. 

If you check the `Environments.json` file in your Project it should NOT have that `dccURL` which is required since release 2.4. Deleting this json file would trigger the `create_default_env.sh` script (via the `Load default environment` build phase). The [default environments file](https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.4.x/src/xcode/ENA/ENA/Resources/Environment/Environments.default.json) does contain that dccURL and should run fine.

**Comment by ndegendogo** [comment]
Thanks for looking into this and for your explanations.
I'll try as soon as I get to my laptop ...

**Comment by ndegendogo** [comment]
@whiskey 
yes, the fix/community-build-june-edition branch does fix the build for me.
Thanks again for your fast support!

**Comment by Ein-Tim** [comment]
Thanks for the feedback @ndegendogo!

@whiskey Thank you for the quick fix and your support! Same goes to @marcussc!

Closing as fixed.
